### ISSUE TITLE
How to configure scalerAddress

### ISSUE THREAD

**Issue by asipras** [wsugarman/durabletask-azurestorage-scaler#208]
First thanks for creating this external scaler for durable functions. I was able to install the scaler successfully on the cluster. However when creating ScaledObject I do not know how to set the **scalerAddress**  property. 

I tried using the value specified in the examples which is , scalerAddress: durabletask-azurestorage-scaler.keda:4370  but that did not work. I get the following message from the keda operator logs . How do I configure the right value for the scalerAddress in ScaledObject?

```
2023-04-19T01:07:15Z    ERROR   external_scaler error   {"type": "ScaledObject", "namespace": "calculationorchestrator", "name": "calcorchestrator", "error": "rpc error: code = Unavailable desc = connection error: desc = **\"transport: Error while dialing: dial tcp: lookup durabletask-azurestorage-scaler.keda on 10.0.0.10:53: no such host\""**}
github.com/kedacore/keda/v2/pkg/scalers.(*externalScaler).GetMetricSpecForScaling
        /workspace/pkg/scalers/external_scaler.go:147
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricSpecForScaling
        /workspace/pkg/scaling/cache/scalers_cache.go:90
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
        /workspace/controllers/keda/hpa.go:206
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
        /workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
        /workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
        /workspace/controllers/keda/scaledobject_controller.go:431
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
        /workspace/controllers/keda/scaledobject_controller.go:229
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
        /workspace/controllers/keda/scaledobject_controller.go:175
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235
```

**Comment by asipras** [comment]
@wsugarman  any help/guidance on this is much appreciated.

**Comment by wsugarman** [comment]
@asipras Sorry for missing this! I'll need to update my notifications to catch these. What does your scaler/chart installation look like? What were the arguments for the helm installation command? The address for the scaler should use the format `<service-name>.<namespace>:<port>` where the defaults should result in `durabletask-azurestorage-scaler.keda:4370` (there is even an example used in my test function chart [here](https://github.com/wsugarman/durabletask-azurestorage-scaler/blob/5543956cb73ddb5f7618c609ec15c89e33e366cf/charts/example-function-app/templates/02-scaledobject.yaml#L20).

**Comment by wsugarman** [comment]
Please re-open if you have more questions or if something still doesn't look right.

**Comment by wsugarman** [comment]
Ah, that's great news! Since both KEDA and the scaler service are in the same namespace, `keda`, you should be able to use `dtfx-scaler.keda:4370` too without `svc.cluster.local`. At least, I think so.
