### ISSUE TITLE
connectionFromEnv not working 

### ISSUE THREAD

**Issue by asipras** [wsugarman/durabletask-azurestorage-scaler#219]
@wsugarman 

I have deployment which I am trying to scale using the durable function scaler.

Here is my deployment file

[deployment .txt](https://github.com/wsugarman/durabletask-azurestorage-scaler/files/11346903/deployment.txt)

As you can see that the deployment references environment variables  from secrets object which has the AzureWebJobsStorage variable configured correctly. 

My secrets file looks like this. In this file I am using TestConnectionString value as place holder, but actually I am using a valid connection string

[secrets.txt](https://github.com/wsugarman/durabletask-azurestorage-scaler/files/11347008/secrets.txt)

However when I try to create scaledobject using this file
[scaledobject.txt](https://github.com/wsugarman/durabletask-azurestorage-scaler/files/11346955/scaledobject.txt)

 I see following error in scaler log 
>2023-04-27T18:31:58.8686248+00:00DurableTask.AzureStorage.Keda[0] => SpanId:f1c87434c1236a99, TraceId:af7780a672b1179f5ce78a62c431e215, ParentId:0000000000000000 => ConnectionId:0HMQ2GTUUMSUQ => RequestPath:/externalscaler.ExternalScaler/GetMetricSpec RequestId:0HMQ2GTUUMSUQ:00000075 Request contain invalid input. System.ComponentModel.DataAnnotations.ValidationException: Unable to resolve the connection string from environment variable 'AzureWebJobsStorage'.    at Keda.Scaler.DurableTask.AzureStorage.Extensions.IValidatableObjectExtensions.EnsureValidated[T](T obj, IServiceProvider serviceProvider) in /scaler/src/Extensions/IValidatableObject.Extensions.cs:line 27    at Keda.Scaler.DurableTask.AzureStorage.DurableTaskAzureStorageScalerService.GetMetricSpec(ScaledObjectRef request, ServerCallContext context) in /scaler/src/DurableTaskAzureStorageScalerService.cs:line 138    at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)    at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)    at Keda.Scaler.DurableTask.AzureStorage.Interceptors.ExceptionInterceptor.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation) in /scaler/src/Interceptors/ExceptionInterceptor.cs:line 70
<6>2023-04-27T18:31:58.8693341+00:00Grpc.AspNetCore.Server.ServerCallHandler[7] => SpanId:f1c87434c1236a99, TraceId:af7780a672b1179f5ce78a62c431e215, ParentId:0000000000000000 => ConnectionId:0HMQ2GTUUMSUQ => RequestPath:/externalscaler.ExternalScaler/GetMetricSpec RequestId:0HMQ2GTUUMSUQ:00000075 Error status code 'InvalidArgument' with detail 'Unable to resolve the connection string from environment variable 'AzureWebJobsStorage'.' raised.
AzureWebJobsStorage'.' raised.

Am I missing something here? Is this how connectionFromEnv  works?

Also If I use connection parameter instead of connectionFromEnv everything works as expected.
Thanks.

**Comment by wsugarman** [comment]
Hi @asipras - The environment variable has to be available to the scaler service itself in its own deployment. So, you'd have to configure the chart when installing to include the appropriate variables like `AzureWebJobsStorage`. You can see the list of possible values in the [README](https://github.com/wsugarman/durabletask-azurestorage-scaler/blob/main/charts/durabletask-azurestorage-scaler/README.md#values).

However, there does not appear to be a hook yet for users to provide a secret reference for their environment variables in the chart, so I'll need to add that.

**Comment by asipras** [comment]
@wsugarman Thanks for the quick reply!!

I now understand that env has to be configured for the scaler deployment for connectionFromEnv to work. I was configuring it for the target deployment and hence it did not work. 

Reading the connection string from the secrets would be really cool feature since user will have to configure the connection in only one place.

**Comment by wsugarman** [comment]
I've published a new version of the chart that now accepts a new value `envFrom`: https://github.com/wsugarman/durabletask-azurestorage-scaler/releases/tag/Chart_1.1.0
